### ISSUE TITLE
Incorrect documentation for trigonometric functions

### ISSUE THREAD

**Issue by nmsmith** [witheve/docs#1]
The documentation for sin, cos and tan currently states that the accepted attributes are:
- degrees
- radians

But in the current version of Eve the functions only accept the attribute "angle" (to my knowledge). I would guess that it is Eve and not the docs that needs updating.

(Also in math.md the word "arithmetic" is misspelt).

**Comment by cmontella** [comment]
Yes, you're right, `angle` is the only accepted attribute. Unfortunately, we're in the awkward position of trying to document a language that's under rapid development, so some of the things that are documented aren't implemented yet or are outdated.  We're aiming to reach a point in the next month or so when the docs and the runtime sync up, but until then things might be out of date.

**Comment by cmontella** [comment]
I'm going to put notes on all the pages with functionality that is not implemented yet.
