### ISSUE TITLE
Database doc page missing some basic concepts

### ISSUE THREAD

**Issue by curioussavage** [witheve/docs#15]
I would make a pull request but I don't understand fully how they work. It seems implied in various place that "databases" are created on demand/ or they are just arbitrary namespaces. It would be great if that were explicitly stated.

A full list of built in databases would be nice too. I believe the http database is one that is missing from the standard lib.

**Comment by cmontella** [comment]
I'm going to work on a big revision of this section in the next week. I'll close this issue when it's done.

**Comment by cmontella** [comment]
Okay, work on this got sidelined, but I added some more "basic concepts" that were missing: https://github.com/witheve/docs/pull/35

The revision that I'm thinking about will move Databases as a top level item in the TOC, and under that I'll have detailed sections for @event, @browser etc.

**Comment by cmontella** [comment]
Alright, I'm satisfied with the current PR, and will merge that in soon, but there's still work to be done in writing docs for the various databases. I think we'll track that in a separate issue.

**Comment by cmontella** [comment]
Okay, the status of databases can be tracked here: https://github.com/witheve/docs/issues/53
