### ISSUE TITLE
Why not JS?

### ISSUE THREAD

**Issue by ccorcos** [witheve/docs#5]

**Comment by cmontella** [comment]
Sorry, I'm not sure what this issue is in relation to... could you explain your question a bit more?

**Comment by ccorcos** [comment]
oops. didnt mean to live this issue haha. but that said, I was just kind of curious why you guys invented an entirely new language. Why not use something that exists already? Lisp, JS, etc.

**Comment by cmontella** [comment]
That's okay, no worries. The short answer is we actually did try using an existing language already, and ran into a lot of problems implementing the features we wanted. Eve was born from LightTable (http://lighttable.com/), which is an IDE for JavaScript/Clojure/Python. It aimed to do some of the same things Eve is doing, like live evaluation, being able to inspect variables during execution, etc.

As the features of light table became more advanced, it became more apparent that today's languages just couldn't keep up with our needs. For instance, non referentially transparent functions make time travel debugging only possible in toy scenarios.

We're working on a doc now that tries to explain all of this in detail, so check back in a about a week or so, and there will be a lot more content to answer this question.

**Comment by ccorcos** [comment]
> For instance, non referentially transparent functions make time travel debugging only possible in toy scenarios.

Amen. 

But I do feel like there's a lot to reinvent... Why not just use a library or a subset of an existing language?

For example, how does composition work? [Given a counter component](https://github.com/witheve/Eve/blob/master/examples/counter.eve), how do I create `n` independent counter components?

**Comment by cmontella** [comment]
> Why not just use a library or a subset of an existing language?

Well like I said, it really comes down to the fact that the semantics of most languages out there just don't fit with the workflow we envision. I gave you the example of referential transparency, but there are other fundamental issues with languages out there, like strict ordering and unguarded mutation that you really can't get around.

There comes a point where you're trying to shoehorn something to fit your intent, when you just say "there's got to be a better way to do this..." Eve is our answer to that.

> Given a counter component, how do I create n independent counter components?

You could do this:

```
search
  i = range[from: 0 to: 6]

commit
  [#counter i count: 0]
```

`i` has a cardinality of 6, so putting it into counter creates 6 independent counters. In general, this is how code reuse and composition happens. For another example, see https://github.com/witheve/Eve/blob/master/examples/clock.eve

Here's the full counter example, updated to the syntax of ts-merge:

build the counter

```
search
  counter = [#counter count]

bind @browser
  [#div counter class: "counter-container", children:
    [#button #count-button class: "button", sort: 1, text: "-", diff: -1, counter]
    [#div class: "count", sort: 2, text: count]
    [#button #count-button style: "cursor: pointer" class: "button", sort: 3, text: "+", diff: 1, counter]]
```

increment the counter

```
search @event @browser @session
  [#click #direct-target element: [#count-button diff counter]]

commit
  counter.count := counter.count + diff
```

go!

```
search
  i = range[from: 0 to: 6]

commit
  [#counter i count: 0]
```

**Comment by ccorcos** [comment]
interesting.

so code reuse is somewhat limited -- if I create a fancy counter, I can't exactly reuse that code to make multiple counters without rewriting the counter component itself...

**Comment by cmontella** [comment]
Actually, you can do that easily. You can commit a `#fancy` counter by just adding the tag:

```
commit
  [#counter #fancy count: 0]
```

And then you can extend the counter like so:

```
search @browser @session
  counter-element = [#div counter]
  counter.tag = "fancy"

bind @browser
  counter-element.style := [border: "1px solid #FF0000"]
```

This says: "For every `#div` with a counter that is also `#fancy`, add a red border.

**Comment by ccorcos** [comment]
Oh interesting... such a bizarre programming model to get used to, but I think I get it now!

One more question -- we can create n independent counters just by committing them, but now what if we want n dependent counters? That is, I want to display n counters that all mirror each other's state. But again, I don't want to have to rewrite any of the counter code for displaying the counter...

I'm not sure I'm explaining this properly but if I can translate this into some pseudocode:

```
// n independent counters:
render (state) => {
  counter(state[0])
  counter(state[1])
  counter(state[2])
}

// n dependent counters:
render (state) => {
  counter(state)
  counter(state)
  counter(state)
}
```
