### ISSUE TITLE
Mention `per` in join documentation

### ISSUE THREAD

**Issue by shamrin** [witheve/docs#57]
[`join` documentation][1] doesn't mention that I can pass `per` argument to `join` function.

It even says "Joins a set of strings into a single string" in the title. To me it suggested that `per` won't work. But [it does work][2]!

[1]: https://github.com/witheve/docs/blob/master/handbook/strings/join.md
[2]: https://gist.github.com/shamrin/e0d52619b79deba1072b7cee0454e4db

**Comment by cmontella** [comment]
Will update!

**Comment by cmontella** [comment]
@shamrin I put up a PR to add this info
